### ISSUE TITLE
Issues page

### ISSUE THREAD

**Issue by bacharakis** [ossn/fixme#4]
- [x] User can select to search issues based on language, expertise and time needed
- [x] When a user clicks on an issue he/she is forwarded to the relevant GitHub issue
- [x] User can sort the issues by newest<>oldest, difficulty level, type, language

P2:
- [x] Issues view: color code on the side of each issue is "a nice to have"
- [x] Fetching and presenting github issues into our platform
