### ISSUE TITLE
Projects page

### ISSUE THREAD

**Issue by bacharakis** [ossn/fixme#5]
- [x] When a user clicks a project he/she is FWDed to a list of issues filtered for that project only
- [x] User has a list of projects he/she can contribute to

P2:
- [ ] When a user clicks a project he/she is FWDed to a project view similar to the beta experiment
